<?php 

namespace AiosAutoPopulate\Routes;

class AiosSlider {
    public function __construct() {
        add_action('rest_api_init', array($this, 'register_endpoints'));
    }

    public function register_endpoints() {
        register_rest_route('aios-populate/v1', '/slider', array(
            'methods'   => 'POST',
            'callback'  => array($this, 'aios_populate_aios_slider'),
        ));
    }

    public function aios_populate_aios_slider($data) {



			$currentDateTime = date('m/d/Y, g:i:s A');

			$dateComplete = get_option('aios_slider_date_complete', $data['date']);

			$jsonData = get_stylesheet_directory_uri() . '/config.json';

			$generatedSlideshow = get_option('aios-slider-autogenerated');

			if (!$generatedSlideshow) {

				$response = wp_remote_get($jsonData, array(
					'timeout' => 45,
					'blocking' => true,
					'cookies' => array()
				));

				$data =  json_decode($response['body']);


				$slider_data = array(
					'post_type'     => 'aios-slider',
					'post_title'    => 'HP Slideshow (Auto Generated)',
					'post_status'   => 'publish',
					'post_author'   => 1,
				);

				$slider_id = wp_insert_post( $slider_data );
			


				// update_option('aios-slider-autogenerated', $slider_id );
				
				$slider_meta = array();
				
				$images = $data->slideshow[0]->images;
				$settings = $data->slideshow[0]->settings[0];


				$ip_banner_uploaded = false;
				foreach ( $images as $index => $image ) {

					$imagesPath = get_stylesheet_directory_uri() . '/' . $image->extension . '/images/';
					$src = media_sideload_image(  $imagesPath . $image->image, null, null, 'id' );

					$slider_meta[] = array(
						'type'    => 'image',
						'image'	  => $src,
						'tagline' => array(
							'title' 	  => $image->title,
							'description' => $image->description,
						),
					);

					// for innerpage image banner
					if ( !$ip_banner_uploaded ) {
						update_option( 'aios-metaboxes-default-banner-image', $src );
						$ip_banner_uploaded = true;
					}
				}
				update_post_meta( $slider_id, '_aios_slider_slides', $slider_meta );

				$slider_settings = array(
					'theme' 			=> array(
						'name'			=> 'default',
						'location'		=> 'core'
					),
					'width'				=> $settings->width,
					'height'			=> $settings->height,
					'min_height'		=> $settings->min_height,
					'min_height_unit'	=> $settings->min_height_unit,
					'transition_speed'	=> $settings->transition_speed,
					'interval'			=> $settings->interval,
					'autoplay'			=> $settings->autoplay,
					'arrows'			=> $settings->arrows,
					'dots'				=> $settings->dots,
					'random'			=> $settings->random,
				);
				update_post_meta( $slider_id, '_aios_slider_settings', $slider_settings );


				update_option('aios_slider_date_complete', $currentDateTime );

				
				$response = array(
					'success' => true, 
					'message' => 'Slideshow Generated', 
					'date' => $dateComplete, 
				);


			}else{
				
				$response = array(
					'success' => false, 
					'message' => 'Slideshow Already Generated', 
					'date' => $dateComplete, 
				);

			}


		return rest_ensure_response($response);
    }
}
new AiosSlider();